# permissions for end users to view meshsources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshsource-viewer-role
rules:
- apiGroups:
  - microservice.slime.io.my.domain
  resources:
  - meshsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - microservice.slime.io.my.domain
  resources:
  - meshsources/status
  verbs:
  - get
