// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/mesh_source.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Zookeeper struct {
	Address              []string `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Root                 string   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zookeeper) Reset()         { *m = Zookeeper{} }
func (m *Zookeeper) String() string { return proto.CompactTextString(m) }
func (*Zookeeper) ProtoMessage()    {}
func (*Zookeeper) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c64ce754c3a3ad4, []int{0}
}
func (m *Zookeeper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zookeeper.Unmarshal(m, b)
}
func (m *Zookeeper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zookeeper.Marshal(b, m, deterministic)
}
func (m *Zookeeper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zookeeper.Merge(m, src)
}
func (m *Zookeeper) XXX_Size() int {
	return xxx_messageInfo_Zookeeper.Size(m)
}
func (m *Zookeeper) XXX_DiscardUnknown() {
	xxx_messageInfo_Zookeeper.DiscardUnknown(m)
}

var xxx_messageInfo_Zookeeper proto.InternalMessageInfo

func (m *Zookeeper) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Zookeeper) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Zookeeper) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

type Eureka struct {
	Address              []string `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	RefreshPeriod        int64    `protobuf:"varint,2,opt,name=refreshPeriod,proto3" json:"refreshPeriod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Eureka) Reset()         { *m = Eureka{} }
func (m *Eureka) String() string { return proto.CompactTextString(m) }
func (*Eureka) ProtoMessage()    {}
func (*Eureka) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c64ce754c3a3ad4, []int{1}
}
func (m *Eureka) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Eureka.Unmarshal(m, b)
}
func (m *Eureka) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Eureka.Marshal(b, m, deterministic)
}
func (m *Eureka) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Eureka.Merge(m, src)
}
func (m *Eureka) XXX_Size() int {
	return xxx_messageInfo_Eureka.Size(m)
}
func (m *Eureka) XXX_DiscardUnknown() {
	xxx_messageInfo_Eureka.DiscardUnknown(m)
}

var xxx_messageInfo_Eureka proto.InternalMessageInfo

func (m *Eureka) GetAddress() []string {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Eureka) GetRefreshPeriod() int64 {
	if m != nil {
		return m.RefreshPeriod
	}
	return 0
}

type MeshSourceSpec struct {
	// Types that are valid to be assigned to Source:
	//	*MeshSourceSpec_Zookeeper
	//	*MeshSourceSpec_Eureka
	Source isMeshSourceSpec_Source `protobuf_oneof:"Source"`
	// 该注册中心会被映射到K8s中哪个namespace
	MappingNamespace     string   `protobuf:"bytes,3,opt,name=mappingNamespace,proto3" json:"mappingNamespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshSourceSpec) Reset()         { *m = MeshSourceSpec{} }
func (m *MeshSourceSpec) String() string { return proto.CompactTextString(m) }
func (*MeshSourceSpec) ProtoMessage()    {}
func (*MeshSourceSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c64ce754c3a3ad4, []int{2}
}
func (m *MeshSourceSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshSourceSpec.Unmarshal(m, b)
}
func (m *MeshSourceSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshSourceSpec.Marshal(b, m, deterministic)
}
func (m *MeshSourceSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshSourceSpec.Merge(m, src)
}
func (m *MeshSourceSpec) XXX_Size() int {
	return xxx_messageInfo_MeshSourceSpec.Size(m)
}
func (m *MeshSourceSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshSourceSpec.DiscardUnknown(m)
}

var xxx_messageInfo_MeshSourceSpec proto.InternalMessageInfo

type isMeshSourceSpec_Source interface {
	isMeshSourceSpec_Source()
}

type MeshSourceSpec_Zookeeper struct {
	Zookeeper *Zookeeper `protobuf:"bytes,1,opt,name=zookeeper,proto3,oneof"`
}
type MeshSourceSpec_Eureka struct {
	Eureka *Eureka `protobuf:"bytes,2,opt,name=eureka,proto3,oneof"`
}

func (*MeshSourceSpec_Zookeeper) isMeshSourceSpec_Source() {}
func (*MeshSourceSpec_Eureka) isMeshSourceSpec_Source()    {}

func (m *MeshSourceSpec) GetSource() isMeshSourceSpec_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *MeshSourceSpec) GetZookeeper() *Zookeeper {
	if x, ok := m.GetSource().(*MeshSourceSpec_Zookeeper); ok {
		return x.Zookeeper
	}
	return nil
}

func (m *MeshSourceSpec) GetEureka() *Eureka {
	if x, ok := m.GetSource().(*MeshSourceSpec_Eureka); ok {
		return x.Eureka
	}
	return nil
}

func (m *MeshSourceSpec) GetMappingNamespace() string {
	if m != nil {
		return m.MappingNamespace
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MeshSourceSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MeshSourceSpec_OneofMarshaler, _MeshSourceSpec_OneofUnmarshaler, _MeshSourceSpec_OneofSizer, []interface{}{
		(*MeshSourceSpec_Zookeeper)(nil),
		(*MeshSourceSpec_Eureka)(nil),
	}
}

func _MeshSourceSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MeshSourceSpec)
	// Source
	switch x := m.Source.(type) {
	case *MeshSourceSpec_Zookeeper:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Zookeeper); err != nil {
			return err
		}
	case *MeshSourceSpec_Eureka:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Eureka); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MeshSourceSpec.Source has unexpected type %T", x)
	}
	return nil
}

func _MeshSourceSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MeshSourceSpec)
	switch tag {
	case 1: // Source.zookeeper
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Zookeeper)
		err := b.DecodeMessage(msg)
		m.Source = &MeshSourceSpec_Zookeeper{msg}
		return true, err
	case 2: // Source.eureka
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Eureka)
		err := b.DecodeMessage(msg)
		m.Source = &MeshSourceSpec_Eureka{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MeshSourceSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MeshSourceSpec)
	// Source
	switch x := m.Source.(type) {
	case *MeshSourceSpec_Zookeeper:
		s := proto.Size(x.Zookeeper)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MeshSourceSpec_Eureka:
		s := proto.Size(x.Eureka)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Zookeeper)(nil), "slime.microservice.v1alpha1.Zookeeper")
	proto.RegisterType((*Eureka)(nil), "slime.microservice.v1alpha1.Eureka")
	proto.RegisterType((*MeshSourceSpec)(nil), "slime.microservice.v1alpha1.MeshSourceSpec")
}

func init() { proto.RegisterFile("api/v1alpha1/mesh_source.proto", fileDescriptor_5c64ce754c3a3ad4) }

var fileDescriptor_5c64ce754c3a3ad4 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x17, 0x27, 0xd5, 0x66, 0x28, 0x92, 0xa7, 0x82, 0x20, 0x65, 0x8a, 0x14, 0xc1, 0x96,
	0x6d, 0xf8, 0xe8, 0xcb, 0x40, 0xd9, 0x8b, 0x22, 0xdd, 0xdb, 0x5e, 0x24, 0xa6, 0xa7, 0x0d, 0x5b,
	0xbc, 0x70, 0x69, 0x07, 0xfa, 0x3f, 0xfa, 0x3f, 0x89, 0x69, 0xeb, 0x0f, 0x84, 0xbe, 0x84, 0xbb,
	0x4b, 0xee, 0x7b, 0xf7, 0xc9, 0x97, 0x9f, 0x48, 0xab, 0xb3, 0xed, 0x44, 0x6e, 0x6c, 0x29, 0x27,
	0x99, 0x01, 0x57, 0x3e, 0x3a, 0xac, 0x49, 0x41, 0x6a, 0x09, 0x2b, 0x14, 0xc7, 0x6e, 0xa3, 0x0d,
	0xa4, 0x46, 0x2b, 0x42, 0x07, 0xb4, 0xd5, 0x0a, 0xd2, 0xee, 0xf9, 0x78, 0xc9, 0xc3, 0x15, 0xe2,
	0x1a, 0xc0, 0x02, 0x89, 0x88, 0xef, 0xc9, 0xa2, 0x20, 0x70, 0x2e, 0x62, 0xf1, 0x30, 0x09, 0xf3,
	0x2e, 0xfd, 0xba, 0xa9, 0xb4, 0x01, 0xac, 0xab, 0x68, 0x27, 0x66, 0xc9, 0x30, 0xef, 0x52, 0x21,
	0xf8, 0x2e, 0x21, 0x56, 0xd1, 0x30, 0x66, 0x49, 0x98, 0xfb, 0x78, 0xbc, 0xe0, 0xc1, 0x4d, 0x4d,
	0xb0, 0x96, 0x3d, 0x8a, 0x67, 0xfc, 0x80, 0xe0, 0x99, 0xc0, 0x95, 0x0f, 0x40, 0x1a, 0x8b, 0x56,
	0xf7, 0x6f, 0x71, 0xfc, 0xc1, 0xf8, 0xe1, 0x1d, 0xb8, 0x72, 0xe9, 0x81, 0x96, 0x16, 0x94, 0xb8,
	0xe5, 0xe1, 0x7b, 0xb7, 0x71, 0xc4, 0x62, 0x96, 0x8c, 0xa6, 0xe7, 0x69, 0x0f, 0x62, 0xfa, 0xcd,
	0xb7, 0x18, 0xe4, 0x3f, 0xad, 0xe2, 0x9a, 0x07, 0xe0, 0x97, 0xf4, 0x93, 0x47, 0xd3, 0xd3, 0x5e,
	0x91, 0x86, 0x67, 0x31, 0xc8, 0xdb, 0x26, 0x71, 0xc1, 0x8f, 0x8c, 0xb4, 0x56, 0xbf, 0xbe, 0xdc,
	0x4b, 0x03, 0xce, 0x4a, 0x05, 0xed, 0x1f, 0xfc, 0xab, 0xcf, 0xf7, 0x79, 0xd0, 0x00, 0xcc, 0xaf,
	0x56, 0xb3, 0x66, 0x8a, 0xc6, 0xcc, 0x07, 0xcd, 0x79, 0x69, 0xb0, 0xa8, 0x37, 0xe0, 0xb2, 0x42,
	0x3b, 0x85, 0x5b, 0xa0, 0xb7, 0xec, 0xb7, 0xa9, 0x4f, 0x81, 0x77, 0x72, 0xf6, 0x19, 0x00, 0x00,
	0xff, 0xff, 0x07, 0xdd, 0xe2, 0x5e, 0xeb, 0x01, 0x00, 0x00,
}
